apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:2clud934HhdjC4Y3PGvDsc9QtH70pl/sCX8V20e/H3De6miTJs2LRw==,iv:Yfefgml3d/HNtkkgkgB03i/3aM3tYb/vNssZgGHc3ks=,tag:vqNMFZcrPTkKa5kSX+aYQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSVJ4d1hMNEprM1BwV0Ra
            U1F0SWpZVUUxWW1QeUYzSi9Qb0tDTlRGa0FZClhJay9kSkExaTI2UFkxUnAvblJB
            MzgveHVmcjBSb2Z0M2xVVUdMeHdjYzAKLS0tIGNQUFJsbWw0MlpoMkl2Uld6K052
            MmM4RThtVS9oK3VNRzhXTWdXbStKYVkKyXfE8RO9Kdw2+43Ply1uusZv49Rbjc8D
            VUw0QON45+JvK/D0xxXnfjJNQX5EyaDxpb+25erZ61DXmlwFPjkHug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-27T11:22:55Z"
    mac: ENC[AES256_GCM,data:sR/eOQBrDR200uopiUK/htvsfRfRTLgGzMTtMIp8eSufd6Ha94JZxCJ7Oy4dCJfRsDuPl/rqFrRM2M3DeOPw0Moy8067Hqq0x9mckiM0naaaRGFd7PeGMSOHtLJHcow/PkwS9KMhCd/gLT2162SnB85HEThZZPimTdaQbwrmzik=,iv:X1roLVuAeUI8LR+bIKky8y2Bs3TWSGfHUyiPDPLP0Ps=,tag:o96lXvk4Gijr6p+UbGi1ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
