---
version: 0.14
mqtt:
  host: mosquitto.home.svc.cluster.local
  topic_prefix: frigate
  port: 1883
  user: "{FRIGATE_MQTT_USERNAME}"
  password: '{FRIGATE_MQTT_PASSWORD}'

ffmpeg:
  global_args: ["-hide_banner", "-loglevel", "warning"]
  hwaccel_args: preset-vaapi

detectors:
  coral:
    type: edgetpu
    device: pci

audio:
  enabled: true
  # https://github.com/blakeblackshear/frigate/blob/dev/audio-labelmap.txt
  listen:
    - fire_alarm
    - speech
    - laughter
    - crying
    - child_singing
    - gasp
    - cough
    - sneeze
    - hiccup
    - wheeze
    - sniff
    - gargling
    - children_playing

record:
  enabled: true

snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 20

go2rtc:
  streams:
    phone_rtsp:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.13:8554/cam/realmonitor?channel=1&subtype=0&authbasic=64
    phone_rtsp_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.13:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
    office:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.4.32:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
    office_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.4.32:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
    garage:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.4.30:554/cam/realmonitor?channel=1&subtype=0&authbasic=64
    garage_sub:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.4.30:554/cam/realmonitor?channel=1&subtype=1&authbasic=64
    front_door:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@10.1.4.10:554/cam/realmonitor?channel=1&subtype=0&authbasic=64#backchannel=0

cameras:
  phone_rtsp:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/phone_rtsp
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/phone_rtsp_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: phone_rtsp
    detect:
      width: 640
      height: 480
      fps: 10
    onvif:
      host: 10.1.4.31
      port: 80
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'

  office:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/office
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/office_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: office
    detect:
      width: 640
      height: 480
      fps: 10
    onvif:
      host: 10.1.4.32
      port: 80
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'

  garage:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: garage
    audio:
      enabled: false
    detect:
      width: 640
      height: 480
      fps: 10
    onvif:
      host: 10.1.4.30
      port: 80
      user: '{FRIGATE_RTSP_USER}'
      password: '{FRIGATE_RTSP_PASSWORD}'

  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_door
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
            - record
      output_args:
        record: preset-record-generic-audio-copy
    live:
      stream_name: front_door
    audio:
      enabled: true
      listen:
        - speech
        - yell
        - water
        - drip
        - footsteps
    detect:
      width: 1920
      height: 1080
      fps: 7
