---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ollama
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: "./kubernetes/apps/ai/ollama/backend"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: external-secrets-stores
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ollama-web-ui
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: "./kubernetes/apps/ai/ollama/ui"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  dependsOn:
    - name: ollama
