apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:fdjwMOkeN8kwKRkVNX2yQS0XIer4mdg+udnYN15C/nEV0Rm6,iv:75gMy+0zNu8eM8iUmEwG6xHHY/XDiMCtAcDb1TXySl0=,tag:noNN6PnnOS8wHvrAgMF20g==,type:str]
    credentials.json: ENC[AES256_GCM,data:AsNNvJq055X5PPsc+D0moPWNU2DaLND34a5+U2G8ubn/UPjyR1u/CSFwN6Yp/0QDifthypBXEm7W/dO2jz6fGQUjuRbgh9/vELl6InQUROcrVQkYyXAOY3kFYmO2UaEVboaYt6VpFMtwEzp4mDzIvS0Tsv8DurhRXEPYLVKSrHhMNzdGGYgEk43YC38dHpB7Xj8EgZxQXLIMoSw75xCBhjYqAXMleRTRWsDY7KgOSw==,iv:Gbdspz3UNVL1DEuc5Qz2tH164ypNLtvUfa3mvm+ZPFQ=,tag:9aTqEq7O8t/JsCcX1RrIBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZWhoTDYvTE9sZWNjclov
            c1pScW5NaXdDcmhJdS8vbWRUSGZZMGl4c0Y4CkdPU2VMcWJOQldraDVUK0pFSitD
            M2Y0UjgyTmFueitiY2U0UzNmR1IrenMKLS0tIExMVUlmVXZtdGpTNmxra0l0dU52
            Tm5xQS9aZ0p5a0RmUzMzMGI0WWpZVlEK2TT2USwptYrezE3hQjj3w0NUPqLfDy8a
            pjIDPJ3OonM7jQhhzOhfIZM7aSEMmCfFw/Yj9GXboS71Bw80hTJkjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-12T13:07:14Z"
    mac: ENC[AES256_GCM,data:trLNho6IhyqAI4ugXWAOhb8OQhVif02NnqflynZ0JrRC3Zd+DRrh3zVb1/cAJ9drj4ZknOO+5/z77BBZaLUrJ3COEQ5ya0NZcr6DrAhmcypkehG+lTJAMVGn5+uTvEv0f1DKlRbMnuVWkHWiunnyHcU1IX8JzJtV6Z4PslG14tk=,iv:zRmSXcm3U1u7GMnLJl9VLjCHNzmsjFjb5q2hl0n1qqs=,tag:d0YQ8SGFKfmoaUyJVFx5ig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
