---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app afterlogic-webmail
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
#    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    controllers:
      afterlogic-webmail:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: afterlogic/docker-webmail-lite
              tag: 9.7.7
            env:
              TZ: ${TIMEZONE}
              # afterlogic-webmailMAIL_DB_DSNW:
              #   valueFrom:
              #     secretKeyRef:
              #       name: database-afterlogic-webmail-user
              #       key: POSTGRES_URL
              #       optional: false

            # resources:
            #   requests:
            #     cpu: 10m
            #     memory: 128Mi
            #   limits:
            #     memory: 512Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 80

    ingress:
      app:
        enabled: true
        className: "internal"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config-afterlogic-php:
        type: configMap
        name: afterlogic-configmap
        defaultMode: 0775
        globalMounts:
          - path: /var/www/html/afterlogic.php
            subPath: afterlogic.php
            readOnly: true
      config-settings-json:
        type: configMap
        name: afterlogic-configmap
        defaultMode: 0775
        globalMounts:
          - path: /var/www/html/data/settings/config.json
            subPath: config.json
            readOnly: true
      # media:
      #   enabled: true
      #   existingClaim: afterlogic-webmail-config-v1
      #   globalMounts:
      #     - path: /var/www/html/data/
      #       retain: true
