apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:71tl75OWWxFgwnDKbEVwUl4CIwje34IhalkWYttqFi6Fdn2Fa5VV1Q==,iv:ycS6BRl6sns2gkJ41cHd2xRSgdR8QHx/WZ1/VCEEego=,tag:N33zwJvvZq3ONnIRT8HwsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwanNMcXU3ZUVwRWUwS3lU
            R0lWTXNvb3IwL3F4RmFIRHd0eU5JY3hRTjJZCkdYb0V6cTl1eE9JYmZkMjVjaFVK
            bUh2ZDd3VStUSk54NThna0dWZThxWUUKLS0tIFc3M2UyVm0xRjdKcTBqSlBZNWI0
            b094N1R2Mys2bjF2Z0ErWFFUNkNENFUKQ3CC+5sAbWsKz8HFW+aQuWz4zfihwKMf
            sKP4M2ff2u9eM9l8dkkeYI7wRtjVhBwBw+coaSKCY+qOhaPIabilUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-13T16:44:16Z"
    mac: ENC[AES256_GCM,data:Sf7dRtmCked+n406rUMLOvxZcB41NHqK7DjLgp7EWNXY5u3YkPkB3AZv9hYFJdDF6lgEVwf2e4+ZMui/AKafYSPEQQkRwfwinitNGmIlMzvYb2iKKS0OGWjgcVAojDTCIn0PGbsNIjjZazPfF2fkqwBP+3EdP0XrUB3E0sRaMJw=,iv:qkVRlWv+zq8bYublbUhf2c1/0RoxuUSZU0q+v1hDevY=,tag:voMe9uBTPP5TNe3o7cctRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
