---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops
spec:
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: cluster-user-auth # weave-gitops expects this name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Admin User
        username: admin
        password: "{{ .WEAVE_GITOPS_ADMIN_PASSWORD }}"
  dataFrom:
  - extract:
      key: weave-gitops
# ---
# # yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: &name oidc-auth
# spec:
#   secretStoreRef:
#     name: bitwarden-secrets-manager
#     kind: ClusterSecretStore
#   refreshInterval: 15m
#   target:
#     name: *name
#     template:
#       engineVersion: v2
#       data:
#         # Authentik
#         clientID: "{{ .GITOPS_CLIENT_ID }}"
#         clientSecret: "{{ .GITOPS_CLIENT_SECRET }}"
#         issuerURL: https://sso.${SECRET_DOMAIN}/application/o/gitops/
#         redirectURL: https://gitops.${SECRET_DOMAIN}/oauth2/callback
#         customScopes: openid,profile,email
#         claimGroups: groups
#         claimUsername: preferred_username
#   dataFrom:
#   - extract:
#       key: weave-gitops
