apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:KYkfHyH8z0zjVajGs8DoDJ3HvyGb0Qhpm9kNRR21s65V0hRIgX71nupJCXhm2k0gnzcI2POEGxEGoXBtGHVOscL4Eaf9yBFl1QMrdn12kVdiU5tN2S9j6CIVa0I1/Q==,iv:B+3cZV/3uDMXxjpA73I2HB1S3QrY3jOsLOhtAHwlWII=,tag:6GcsWINAhd3xUwKUi4Au5Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7er6e8tNnf4pbCpxrpiZ,iv:vX0rK2aa9IqhE4WmqScaKe4dmfBRqtNKorWz9Cvc6Y8=,tag:yZTEHLCElsRSrV4M5LOc5w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:pbyIegog4IFnLsPzwV/xOX9cRc7N,iv:m6krlB1pwv5dEGTMQwScxM0Y5AFU7dnbyIkCFFjjMYM=,tag:aEig2UTupG/NrHDqyFPtrw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KgY+5NODO4TZO71W9Wb1DsnkLxvtYRwkNO0zNeZEj2LSDyLS,iv:aC9RY1WEnfzVlSt5C6oyp9EPMVfSkbQJPsRSEcsQp8I=,tag:VCyJtSOR9MMGKb+uy4zJzA==,type:str]
    SVC_MC_ADDR: ENC[AES256_GCM,data:puCqdzGP6Tr2EblnS5I=,iv:MpNWIE3mykOW5tYAnbFXZU4GRxuL5NxpsYmegyfaWGs=,tag:ih0yGiB+vh/kfdYvI4bWiw==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:Wp5z+sxZsapjAy8VrB8=,iv:AlMm/xJ15IwSvbx1dw47sgDzC1kDhpu/oNUB3zCnrtM=,tag:aAZwfmqM+zfwMcyFY5CM8A==,type:str]
    PI3B_IP: ENC[AES256_GCM,data:njOWTLT0C3yuKeR1HQ==,iv:Msz44NpEiOy58Y/7KuznJX7qfnAFQbxpZLG/ZbZIh2Y=,tag:gmsdfsTxiKPjArvPAb30tA==,type:str]
    SVC_PLEX_ADDR: ENC[AES256_GCM,data:o/E5Kwfvh85IV3Vz5Dg=,iv:bqZ73FY8FK1IxdkE2ohaqf3rbIueuUbIW8t+hbv38Dc=,tag:t/yNKBm4mYy2TmddlkZvbQ==,type:str]
    SVC_POSTGRES_ADDR: ENC[AES256_GCM,data:NSx3JEF56+S7vpAI5wo=,iv:ZW4zzgWNmcWCIgujKkDtyFe9Kcvsi2onhwD87dQHdOk=,tag:HQvSvYd6RfDvs86Vo+toZQ==,type:str]
    SVC_QBITTORENT_ADDR: ENC[AES256_GCM,data:JICYK0qJpvjwYO6L5MM=,iv:ERcTbzv+oB0N4crQeMHiIFG32qIxCnfjZUL2eSVRih8=,tag:VmGpFGdOd5AUNfUXjmZ7Ww==,type:str]
    SVC_LOCALAI_ADDR: ENC[AES256_GCM,data:DkBTgbYgHIjl1VuXbRo=,iv:yiY7im8HppvgAVfGrRvlZwF9eEXIvc8Y5jfMBR4JlLk=,tag:ZnKJ2XJpjJ0xqOGwUJsO6Q==,type:str]
    SVC_SMTP_ADDR: ENC[AES256_GCM,data:RVdN64L0u5PnCk5XSaA=,iv:DlCtDmGqM/Env1fVS7gfzd9k5rO15zsTJZ2x1q6vzL4=,tag:hsXms2TvCmRMFPs41lmZBA==,type:str]
    SVC_UNIFI_ADDR: ENC[AES256_GCM,data:QbzVv0sYKQVGuq8UUnI=,iv:ssjMA4fskgq+voWvAdnzD+oDL0HOhrDFk/S/flqtOps=,tag:ADqWi4Gu3SnBOmFJ3/0MgQ==,type:str]
    NAS_IP: ENC[AES256_GCM,data:2+Ao2NrVdFduIikkYg==,iv:no8G3rcL1+e7luURGuUTdZXTx0iE6eMm/0k92JYSUwg=,tag:mJWYoSR79dPtkSNl0LRRpA==,type:str]
    HASS_PI4: ENC[AES256_GCM,data:mBlbacBJSWZjFU1i7Q==,iv:zMyQWh/kkI1RItBj/e8vDzPFkzAsK7F1ykJn267UAz0=,tag:+6+g5buAtLzHDxSHf26oHA==,type:str]
    HASS_YELLOW: ENC[AES256_GCM,data:xedaDK4AMFY0VKLI6w==,iv:dJ3KtSVfKsIyqrCMd4YNjm+xi2gdiMIxCuWXJ/flcS0=,tag:g5071CL1apyYXgrZX6RYhw==,type:str]
    PIHOLE_IP: ENC[AES256_GCM,data:5D0lkI7jUR2n14R21zs=,iv:mTnr187oEem5Vogt8qCx09adWHSKjUy9J/rhKjc12oc=,tag:W5AF8hTrf5HWGtNhyX7tZQ==,type:str]
    SYN_MINIO: ENC[AES256_GCM,data:LVMYIWwuqiuxWHm8YGA=,iv:b29Y8TbR7xg9YwasUVSzXdzN1U5QieQ0g3Z7DP73Yz8=,tag:mgkOBfJkZaY7ZRhaCm/yqA==,type:str]
    PVE1_IP: ENC[AES256_GCM,data:ia1LpDRYKzAeE40guw==,iv:u8LUdWnX8hpdiqsKJ7it2onuQL2jiQUNS9rIASaPerA=,tag:ZYe+m9rDbZmzFGY/gil2BA==,type:str]
    PVE2_IP: ENC[AES256_GCM,data:SYgLrRM2ssU9wlyPtg==,iv:Q+a520xjGCIVtR53PTZ8ofxnMeG8Uk9g5YulFekhWtk=,tag:6r7l1VoRXQBcf/HdTLm9Zw==,type:str]
    PVE3_IP: ENC[AES256_GCM,data:Z/CsuOfpB/3cQWWPnQ==,iv:gcNZa2tjytd9oH1uU6zP9rmgyYUOMJGLH5abbTRovhw=,tag:pipZxHGfLektEQwowPsFsg==,type:str]
    NFS_SERVER_CAMERAS_DIR: ENC[AES256_GCM,data:yYXfb46awgOzfV2r0zv4hSAU2XhApddkoUa/tRvsgtxqeyiV9AFxg2RBGw==,iv:MOArbtmpSamQQrYBkVNKvVrA92IcWCvll9/0KhLrejw=,tag:+zMRewyMri1L/PFKYsLUoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWjBJTWwzYVpTNCtyZlZS
            VnlkclNqWGhwck5FV09rVUNIVkh3Q0s1R1NBCk1CS1lmRUhwUm95RFpBZjYxNHRB
            QnZFRjUxOWxQejIzNHY3M0JGb2Rmc28KLS0tIDlLTG5Ob2pvMDA2SG4yUklQejMw
            UytwZWtFK1d2N2h5VytXc29MazRNRE0KgRfIvlEJZqxjfb4oi1b0ZEi3PbTXdySD
            TQOvaKu5C5oyJb8cTYCdbBf8phg3l92ymgov2Hut3BK7Wj+tv7HRrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-18T08:07:05Z"
    mac: ENC[AES256_GCM,data:B4jYXZBA3I36SU+4vCkrpV0p/5+H3pwc/9noyfaKTbkZeJOZLcemi+0i3t8epMMAIaJD86qufFtz2pukrYiSdo9AM9RgfM14W38KxmAuydvtJLVkVvWrqanqDkh/GX1Vr2AIn31uLmo+KRmJeKNO4HxnsNsggr0lM3uFhfBcaUo=,iv:8ZMdeTRruVjVMV0j5R815y0gU93oGUzsq3ePKQPOFIg=,tag:ThvEzMZIpjdv8YUInakxDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
