apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:KYkfHyH8z0zjVajGs8DoDJ3HvyGb0Qhpm9kNRR21s65V0hRIgX71nupJCXhm2k0gnzcI2POEGxEGoXBtGHVOscL4Eaf9yBFl1QMrdn12kVdiU5tN2S9j6CIVa0I1/Q==,iv:B+3cZV/3uDMXxjpA73I2HB1S3QrY3jOsLOhtAHwlWII=,tag:6GcsWINAhd3xUwKUi4Au5Q==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:7er6e8tNnf4pbCpxrpiZ,iv:vX0rK2aa9IqhE4WmqScaKe4dmfBRqtNKorWz9Cvc6Y8=,tag:yZTEHLCElsRSrV4M5LOc5w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:pbyIegog4IFnLsPzwV/xOX9cRc7N,iv:m6krlB1pwv5dEGTMQwScxM0Y5AFU7dnbyIkCFFjjMYM=,tag:aEig2UTupG/NrHDqyFPtrw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:KgY+5NODO4TZO71W9Wb1DsnkLxvtYRwkNO0zNeZEj2LSDyLS,iv:aC9RY1WEnfzVlSt5C6oyp9EPMVfSkbQJPsRSEcsQp8I=,tag:VCyJtSOR9MMGKb+uy4zJzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWjBJTWwzYVpTNCtyZlZS
            VnlkclNqWGhwck5FV09rVUNIVkh3Q0s1R1NBCk1CS1lmRUhwUm95RFpBZjYxNHRB
            QnZFRjUxOWxQejIzNHY3M0JGb2Rmc28KLS0tIDlLTG5Ob2pvMDA2SG4yUklQejMw
            UytwZWtFK1d2N2h5VytXc29MazRNRE0KgRfIvlEJZqxjfb4oi1b0ZEi3PbTXdySD
            TQOvaKu5C5oyJb8cTYCdbBf8phg3l92ymgov2Hut3BK7Wj+tv7HRrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-17T03:02:57Z"
    mac: ENC[AES256_GCM,data:BgOJLfB9COPHMsgd5ZHM9QujrEWwuON9Anba5YSDw75wNHS+lfvqWriphwsbhmSf8fIqJdD13uliagBsS7cwMxTHnZRplhoM7YHcndpmtsSuMGxgUvswv4aoV9cbxXAlOb6DKpOb6OKab8wGNLZHnjJO9p4CkZmNTo7ZVMKqatI=,iv:iKLwp+qmyeHoIPLSG7NZqvoxlUxU1Wdub2vL0CzPS7c=,tag:UxLikf5IrJEv9MEjIdkXhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
