apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: plex-minio-rsrc
  namespace: media
spec:
  sourcePVC: plex-config-0
  trigger:
    schedule: "0 * * * *"
  restic:
    copyMethod: Direct
    pruneIntervalDays: 14
    repository: plex-restic-secret
    storageClassName: local-hostpath
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
